[config] Do not tread compiler warnings as errors
The drivers added by StarFive throw a lot of compiler warnings, treated as errors by defautl, either since a recent upstream Linux update, or a change in the compiler.
At least in the AIC8800 driver, the missing break or return statement is intended:

```
drivers/net/wireless/aic8800/aic8800_fdrv/rwnx_msg_tx.c: In function ‘rwnx_send_add_if’:
drivers/net/wireless/aic8800/aic8800_fdrv/rwnx_msg_tx.c:616:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
  616 |         add_if_req_param->p2p = true;
      |         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
drivers/net/wireless/aic8800/aic8800_fdrv/rwnx_msg_tx.c:619:5: note: here
  619 |     case NL80211_IFTYPE_STATION:
      |     ^~~~
drivers/net/wireless/aic8800/aic8800_fdrv/rwnx_msg_tx.c:629:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
  629 |         add_if_req_param->p2p = true;
      |         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
drivers/net/wireless/aic8800/aic8800_fdrv/rwnx_msg_tx.c:632:5: note: here
  632 |     case NL80211_IFTYPE_AP:
      |     ^~~~
  CC [M]  drivers/net/wireless/intel/iwlwifi/iwl-debug.o
cc1: all warnings being treated as errors
```

```
    #ifdef CONFIG_RWNX_FULLMAC
    //case NL80211_IFTYPE_P2P_DEVICE:
    case NL80211_IFTYPE_P2P_CLIENT:
        add_if_req_param->p2p = true;
        // no break
    #endif /* CONFIG_RWNX_FULLMAC */
    case NL80211_IFTYPE_STATION:
        add_if_req_param->type = MM_STA;
        break;

    case NL80211_IFTYPE_ADHOC:
        add_if_req_param->type = MM_IBSS;
        break;

    #ifdef CONFIG_RWNX_FULLMAC
    case NL80211_IFTYPE_P2P_GO:
        add_if_req_param->p2p = true;
        // no break
    #endif /* CONFIG_RWNX_FULLMAC */
```

As a tradeoff between serving a kernel containing bad quality code and serving expected kernel features, we accept them now, as it was with Linux 5.15 builds before.

Signed-off-by: MichaIng <micha@dietpi.com>